### ISSUE TITLE
Implementar CQRS

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/feature_step#15]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/feature_step/issues/16
- [ ] https://github.com/alercebroker/feature_step/issues/17
- [ ] https://github.com/alercebroker/pipeline_monorepo/issues/45
- [ ] https://github.com/alercebroker/kubernetes_pipeline/issues/34
```

![Image](https://user-images.githubusercontent.com/18015991/216419656-b1358df1-ede2-4639-aa9e-b416c55a4118.png)
