### ISSUE TITLE
Refactor Features step

### ISSUE THREAD

**Issue by pgallardor** [alercebroker/feature_step#22]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/feature_step/issues/26
- [ ] https://github.com/alercebroker/feature_step/issues/27
- [ ] https://github.com/alercebroker/feature_step/issues/29
- [ ] https://github.com/alercebroker/feature_step/issues/30
```

Que hacer en caso de recibir detecciones de un survey distinto a ZTF:
- En resumen, evitar que se caiga con otros surveys.
- Lo que se calcule desde extra_fields debe estar previamente identificado.
